name: True Clouds
favicon: null
layout_spectrum: 0.6623318532947451
typography_spectrum: 0.6750497429165989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#009ede'
    - '#706f6f'
    - '#606060'
    - '#0092db'
    - '#0055aa'
  brandStrength: 0.3519086427986622
  lightness: 0.42391875199973583
  saturation: 0.10356927569955587
  rhythmicContrast: 0.49568886356428266
purpose: []
