typography_spectrum: 0.8920864050742239
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.10920759220607579
  lightness: 0.2504084713291377
  saturation: 0.6830674638040364
  rhythmicContrast: 0.635132391937077
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.01618118048645556
analytics:
  google: null
  facebook: null
  twitter: null
name: Konnect Global
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
