name: True Clouds
favicon: null
layout_spectrum: 0.3344791205599904
typography_spectrum: 0.576259397668764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.8464995492249727
  lightness: 0.49190266733057797
  saturation: 0.14630750799551606
  rhythmicContrast: 0.9472311642020941
purpose: []
