typography_spectrum: 0.6750497429165989
color:
  brandColors:
    - '#009ede'
    - '#008080'
    - '#0080ff'
    - '#0080bf'
    - '#0000ff'
  brandStrength: 0.3519086427986622
  lightness: 0.42391875199973583
  saturation: 0.10356927569955587
  rhythmicContrast: 0.49568886356428266
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.97551
analytics:
  google: null
  facebook: null
  twitter: null
name: Konnect Global
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
