typography_spectrum: 0.3080277843400836
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.6836462467908859
  lightness: 0.10540401935577393
  saturation: 0.4140749932266772
  rhythmicContrast: 0.5758670328650624
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6514379167929292
analytics:
  google: null
  facebook: null
  twitter: null
name: Konnect Global
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
