typography_spectrum: 0.6263310331851244
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.8304099340457469
  lightness: 0.25833455682732165
  saturation: 0.9417862275149673
  rhythmicContrast: 0.2285429323092103
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5281991455703974
analytics:
  google: null
  facebook: null
  twitter: null
name: Konnect Global
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
